# Generated by Django 5.1.6 on 2025-02-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
